Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g4, pull requests merged in 2022-11, with the labels that each got.

#67 Add mock auth and fix tests
  backend/collab-service/package-lock.json
  backend/collab-service/package.json
  backend/collab-service/src/auth/auth.js
  backend/collab-service/src/routes/routes.js
  backend/collab-service/src/service/controller.js
  backend/collab-service/src/service/service.js
  backend/collab-service/src/sockets/pubsub-socket.js
  backend/collab-service/src/sockets/session-socket.js
  backend/collab-service/test/test.js
  backend/matching-service/package-lock.json
  backend/matching-service/package.json
  backend/matching-service/src/auth/auth.js
  backend/matching-service/src/routes/routes.js
  backend/matching-service/src/service/controller.js
  backend/matching-service/src/sockets/match-socket.js
  backend/matching-service/test/mock-pubsub.js
  backend/matching-service/test/test.js
  backend/room-service/package-lock.json
  backend/room-service/package.json
  backend/room-service/src/auth/auth.js
  backend/room-service/src/routes/routes.js
  backend/room-service/src/service/caller.js
  backend/room-service/src/service/controller.js
  backend/room-service/test/test.js
  frontend/src/pages/DifficultySelector.js
Labels: nice to have

#68 Add docker compose capability
  backend/question-service/.dockerignore
  backend/question-service/.env.example
  backend/question-service/Dockerfile
  backend/question-service/app/question/connector.py
  backend/question-service/app/question/create_tables.py
  backend/question-service/app/question/question_crud.py
  backend/question-service/app/soupScrape.py
  backend/question-service/docker-compose.yml
  backend/question-service/main.py
  backend/question-service/run.sh
  docker-compose.yml
Labels: nice to have

#69 Add CI tests
  .github/workflows/ci-tests.yaml
  backend/collab-service/Dockerfile.dev
  backend/collab-service/run.sh
  backend/matching-service/Dockerfile.dev
  backend/matching-service/run.sh
  backend/pubsub-service/Dockerfile.dev
  backend/pubsub-service/run.sh
  backend/room-service/Dockerfile.dev
  backend/room-service/run.sh
Labels: nice to have

#73 Update docker scripts
  README.md
  frontend/src/pages/LoadingPage.js
  run-backend.sh
  run-docker.sh
  run-frontend.sh
  run-tests.sh
Labels: deployment

#75 Branch UI updates
  frontend/public/index.html
  frontend/src/assets/loading.svg
  frontend/src/components/CodeBox.css
  frontend/src/components/CodeBox.js
  frontend/src/components/buttons/ChangePasswordButton.js
  frontend/src/components/buttons/DeleteUserButton.js
  frontend/src/components/buttons/UpdateUsernameButton.js
  frontend/src/components/form/UpdateDetailsForm.js
  frontend/src/components/loading.js
  frontend/src/pages/LoadingPage.css
  frontend/src/pages/LoadingPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/pages/RoomPage.js
  frontend/src/pages/UserHistoryPage.js
Labels: frontend
